'use client'

import { useState, useEffect } from 'react'
import { AGGREGATION_EXPLANATION } from '@/lib/ranking'

export function PhaseRanking({
  session,
  participantId,
  group,
  round,
}: {
  session: any
  participantId: string
  group: any
  round: 'INITIAL' | 'REVISED'
}) {
  const [rankings, setRankings] = useState<Record<string, number>>({}) // candidateId → rank
  const [submitted, setSubmitted] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const candidates = round === 'INITIAL'
    ? group?.candidates?.initial || []
    : group?.candidates?.revised || []

  // Check if already ranked
  useEffect(() => {
    fetch(`/api/ranking?participantId=${participantId}&round=${round}`)
      .then(r => r.json())
      .then(data => {
        if (data.hasRanked) {
          const map: Record<string, number> = {}
          for (const r of data.rankings) {
            map[r.candidateId] = r.rank
          }
          setRankings(map)
          setSubmitted(true)
        }
      })
      .catch(() => {})
  }, [participantId, round])

  function assignRank(candidateId: string, rank: number) {
    setSubmitted(false)
    setRankings(prev => {
      const next = { ...prev }
      // If another candidate already has this rank, swap them
      const existingHolder = Object.entries(next).find(
        ([id, r]) => r === rank && id !== candidateId
      )
      if (existingHolder) {
        // Give the displaced candidate the rank the current one had (if any)
        if (next[candidateId]) {
          next[existingHolder[0]] = next[candidateId]
        } else {
          delete next[existingHolder[0]]
        }
      }
      next[candidateId] = rank
      return next
    })
  }

  const allRanked = candidates.length === 4 && Object.keys(rankings).length === 4

  async function handleSubmit() {
    if (!allRanked) return
    setSaving(true)
    setError('')
    try {
      const res = await fetch('/api/ranking', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          participantId,
          rankings: Object.entries(rankings).map(([candidateId, rank]) => ({
            candidateId,
            rank,
          })),
        }),
      })
      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error)
      }
      setSubmitted(true)
    } catch (err: any) {
      setError(err.message)
    } finally {
      setSaving(false)
    }
  }

  // Waiting for generation
  if (candidates.length === 0) {
    return (
      <div className="bg-white rounded-lg shadow-sm border p-6 text-center">
        <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-blue-50 mb-3">
          <span className="text-2xl">🤖</span>
        </div>
        <h3 className="text-lg font-semibold text-slate">Generating Statements…</h3>
        <p className="text-sm text-gray-500 mt-1">
          The AI is drafting candidate group statements based on your opinions. This may take a moment.
        </p>
      </div>
    )
  }

  // Show winner if tallied
  const winner = candidates.find((c: any) => c.isWinner)
  const showResults = candidates.some((c: any) => c.bordaScore > 0)

  const rankingCount = round === 'INITIAL'
    ? group?.initialRankingCount || 0
    : group?.revisedRankingCount || 0
  const groupTotal = group?.participantCount || 0

  return (
    <div className="space-y-4">
      {/* Transparency notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-md p-3 text-xs text-amber-800">
        ⚠️ These statements were generated by an AI based on your group&apos;s opinions.
        They may contain errors or miss nuances. {round === 'REVISED'
          ? 'These revisions incorporate your critiques.'
          : 'The critique phase will let you correct any problems.'}
      </div>

      {/* Aggregation explanation */}
      <div className="bg-blue-50 border border-blue-200 rounded-md p-3 text-xs text-blue-800">
        📊 {AGGREGATION_EXPLANATION}
      </div>

      <h3 className="text-lg font-semibold text-slate">
        {round === 'INITIAL' ? 'Rank Initial Candidates' : 'Rank Revised Candidates'}
      </h3>
      <p className="text-sm text-gray-600">
        Click the numbered buttons to assign a rank (1 = best, 4 = worst) to each candidate.
        For instance, you would rank a candidate statement 1 if it is closest to what you believe; 4 if it is furthest from what you believe.
      </p>

      {/* Candidate cards */}
      <div className="space-y-4">
        {candidates.map((c: any) => {
          const myRank = rankings[c.id]
          return (
            <div
              key={c.id}
              className={`bg-white rounded-lg border-2 p-4 transition-colors ${
                myRank === 1
                  ? 'border-green-400 bg-green-50/30'
                  : myRank
                  ? 'border-blue-200'
                  : 'border-gray-200'
              } ${showResults && c.isWinner ? 'ring-2 ring-yellow-400' : ''}`}
            >
              <div className="flex items-start gap-3">
                {/* Rank buttons */}
                <div className="flex flex-col gap-1 shrink-0">
                  {[1, 2, 3, 4].map(rank => (
                    <button
                      key={rank}
                      onClick={() => assignRank(c.id, rank)}
                      disabled={submitted && !saving}
                      className={`w-8 h-8 rounded-md text-xs font-bold transition-colors ${
                        myRank === rank
                          ? rank === 1
                            ? 'bg-green-500 text-white'
                            : 'bg-primary text-white'
                          : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
                      } disabled:cursor-default`}
                      title={`Rank ${rank}`}
                    >
                      {rank}
                    </button>
                  ))}
                </div>

                {/* Statement content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-medium text-gray-400">
                      Candidate {c.index + 1}
                    </span>
                    {myRank && (
                      <span className={`text-xs px-1.5 py-0.5 rounded ${
                        myRank === 1 ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'
                      }`}>
                        Your #{myRank}
                      </span>
                    )}
                    {showResults && (
                      <span className={`text-xs px-1.5 py-0.5 rounded ${
                        c.isWinner ? 'bg-yellow-100 text-yellow-800 font-semibold' : 'bg-gray-100 text-gray-600'
                      }`}>
                        {c.bordaScore} pts{c.isWinner ? ' — Winner!' : ''}
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-gray-800 leading-relaxed">{c.text}</p>
                  <p className="text-xs text-gray-500 mt-2 italic">
                    Rationale: {c.rationale}
                  </p>
                </div>
              </div>
            </div>
          )
        })}
      </div>

      {/* Submit */}
      {!showResults && (
        <div className="flex items-center justify-between">
          <p className="text-xs text-gray-500">
            {allRanked ? 'All candidates ranked!' : `Assign ranks 1–4 to all candidates`}
          </p>
          <button
            onClick={handleSubmit}
            disabled={!allRanked || saving || submitted}
            className="bg-primary text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-primary-dark disabled:opacity-50 transition-colors"
          >
            {saving ? 'Saving…' : submitted ? '✓ Submitted' : 'Submit Rankings'}
          </button>
        </div>
      )}
      {error && <p className="text-sm text-red-600">{error}</p>}

      {submitted && !showResults && (
        <div className="bg-green-50 border border-green-200 rounded-md p-3">
          <p className="text-sm text-green-700">
            ✓ Rankings submitted! Waiting for others…
            ({rankingCount}/{groupTotal} ranked)
          </p>
        </div>
      )}
    </div>
  )
}
